/*
 * This file is generated by jOOQ.
 */
package com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.tables;


import com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.Keys;
import com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.Public;
import com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.tables.records.VoterRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Voter extends TableImpl<VoterRecord> {

    private static final long serialVersionUID = -1456380118;

    /**
     * The reference instance of <code>public.voter</code>
     */
    public static final Voter VOTER = new Voter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VoterRecord> getRecordType() {
        return VoterRecord.class;
    }

    /**
     * The column <code>public.voter.id</code>.
     */
    public final TableField<VoterRecord, UUID> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.voter.first_name</code>.
     */
    public final TableField<VoterRecord, String> FIRST_NAME = createField(DSL.name("first_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.voter.last_name</code>.
     */
    public final TableField<VoterRecord, String> LAST_NAME = createField(DSL.name("last_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>public.voter</code> table reference
     */
    public Voter() {
        this(DSL.name("voter"), null);
    }

    /**
     * Create an aliased <code>public.voter</code> table reference
     */
    public Voter(String alias) {
        this(DSL.name(alias), VOTER);
    }

    /**
     * Create an aliased <code>public.voter</code> table reference
     */
    public Voter(Name alias) {
        this(alias, VOTER);
    }

    private Voter(Name alias, Table<VoterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Voter(Name alias, Table<VoterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Voter(Table<O> child, ForeignKey<O, VoterRecord> key) {
        super(child, key, VOTER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<VoterRecord> getPrimaryKey() {
        return Keys.VOTER_PKEY;
    }

    @Override
    public List<UniqueKey<VoterRecord>> getKeys() {
        return Arrays.<UniqueKey<VoterRecord>>asList(Keys.VOTER_PKEY);
    }

    @Override
    public Voter as(String alias) {
        return new Voter(DSL.name(alias), this);
    }

    @Override
    public Voter as(Name alias) {
        return new Voter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Voter rename(String name) {
        return new Voter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Voter rename(Name name) {
        return new Voter(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
