/*
 * This file is generated by jOOQ.
 */
package com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq;


import com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.tables.FlywaySchemaHistory;
import com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.tables.Voter;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.voter</code>.
     */
    public static final Voter VOTER = Voter.VOTER;
}
