/*
 * This file is generated by jOOQ.
 */
package com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.tables.records;


import com.hexarchbootdemo.adapter.output.persistence.h2.generated_sources.jooq.tables.Voter;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VoterRecord extends UpdatableRecordImpl<VoterRecord> implements Record3<UUID, String, String> {

    private static final long serialVersionUID = 1801580303;

    /**
     * Setter for <code>VOTER.VOTER.ID</code>.
     */
    public VoterRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>VOTER.VOTER.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>VOTER.VOTER.FIRST_NAME</code>.
     */
    public VoterRecord setFirstName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>VOTER.VOTER.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VOTER.VOTER.LAST_NAME</code>.
     */
    public VoterRecord setLastName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>VOTER.VOTER.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Voter.VOTER_.ID;
    }

    @Override
    public Field<String> field2() {
        return Voter.VOTER_.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Voter.VOTER_.LAST_NAME;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public VoterRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public VoterRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public VoterRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public VoterRecord values(UUID value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoterRecord
     */
    public VoterRecord() {
        super(Voter.VOTER_);
    }

    /**
     * Create a detached, initialised VoterRecord
     */
    public VoterRecord(UUID id, String firstName, String lastName) {
        super(Voter.VOTER_);

        set(0, id);
        set(1, firstName);
        set(2, lastName);
    }
}
